let userSeq=[];//this will store all swq gen by user it will beocme empty at every lovel
let gameSeq=[];//this will store all random seq gen by game , it will get empty only when game is over 
let level=0;
let score=[];//we will calc highest score from it
let started=false;
let btns=["red","yellow","blue","green"];//stores all btns as color names
let currentScore=0;





let timer;
let timeLeft=10;


//s1 start 
document.addEventListener("keypress",function()
{   
    if(started==false)
    {  started=true; //now once game is started again it will not run * can it be replaced by on load event - no beocz restart is dependent on that 
       levelup();
       console.log("game started!");
    }
})

let h2=document.querySelector("h2");
//s2 - level up 
function levelup()
{ userSeq=[]; //empty user seq arr every time level inc  
//why game seq is not emtied here 
  //gameSeq stores the entire sequence of colors generated by the game so far.
// Each level adds one new color to the sequence.
// The player must repeat the full sequence correctly to advance.
//   level++;
//   console.log("level up");
//   h2.innerText=`level ${level}`;

  //s3
  level++;
  h2.innerHTML=`level ${level}`;

  timeLeft=10;//reset timer
  startCountdown();//start counter
  ranColorGen();
}

function ranColorGen()
{
//lets generate a ran idx to choose b/w 4 btns
 let ranIdx=Math.floor(Math.random()*4);//0-3 idx gen randomly
 let ranColor=btns[ranIdx];//get color stored at that index 
 console.log("random generated color ="+ranColor);
 ranBtn=document.getElementById(ranColor);//the html elem div has class with value of color 

 gameSeq.push(ranColor);//store the color gen reandomly i ngame seq arr
 console.log("game seq "+gameSeq);
 gameFlash(ranBtn);//add gameflash class in ranbtn 
 
}

//s4 game and user flash 
function gameFlash(ranBtn)
{
    ranBtn.classList.add("gameflash");
     console.log("game button flashed")
    setTimeout(function()
{
    ranBtn.classList.remove("gameflash");
},450)
}
function userFlash(ranBtn)
{
    ranBtn.classList.add("userflash");
    console.log("user button flashed")
    setTimeout(function()
{
    ranBtn.classList.remove("userflash");
},450)
}

//s5 adding event listeneres on button
let allBtns=document.querySelectorAll(".btn");
for(let btn of allBtns)
{
    btn.addEventListener("click",btnPress);
}

//s6 user seq update
function btnPress()
{
    console.log(this);//the button pressed by user 
    let userBtn=this;
    userFlash(userBtn); //flash the btn pressed by user by adding class
    let userColor=userBtn.getAttribute("id");//it will return the color of btn pressed by user
    userSeq.push(userColor);
    console.log("user seq ="+ userSeq);
    checkAns(userSeq.length-1);//comapare the last idx
}

//s7 checking ans
function checkAns(idx)
{  if(userSeq[idx]===gameSeq[idx])
   { if(userSeq.length===gameSeq.length) //when len of both arr and their last leems the users clears the level
{ setTimeout(levelup,1000);
}  
   }
  else
  {  currentScore=(level-1)*10;
     if(currentScore<0)
     {
        currentScore=0;
     }
     score.push(currentScore);


    h2.innerHTML=`Game Over !<b> Your score was ${currentScore}</b> Press any key to restart`;
    document.querySelector("body").style.backgroundColor="red";

    setTimeout(function()
{   
    document.querySelector("body").style.backgroundColor="white";

},150);
  
  console.log("game over!");

  calcHighestScore();
  restart();
}
}

//s8-
//restart game
function restart()
{
    gameSeq=[];
    started=false;
    userSeq=[];
    level=0;
}

//hw
//s9- calc highest score
function calcHighestScore()
{
    let h3=document.querySelector("h3");
    let highestScore=Math.max(...score);
    if(highestScore<0)
        {
            highestScore=0;
        }
    console.log("highest score= "+highestScore);
   
    h3.innerHTML=`Highest score ${highestScore}`;
}

function startCountdown()
{
    clearInterval(timer);//stop any prev timer

    timer=setInterval(()=>//t’s like a ticking clock. Every 1 second, it runs the code inside it. Here's what happens each tick:
    { timeLeft--;
     document.querySelector("h4").innerText=`Time left :${timeLeft}s`;

    if(timeLeft<=0)//if timer has reached zero - game over
    { clearInterval(timer);
      currentScore=(level-1)*10;
      score.push(currentScore);

      h2.innerHTML=`Times up ! <b> your score was ${currentScore}</b> Press any key to restart`;
      document.querySelector("body").style.backgroundColor="red";

    setTimeout(function()
{   
    document.querySelector("body").style.backgroundColor="white";

},150);
  
  console.log("game over!");

  calcHighestScore();
  restart();
  }

},1000);
}